#系统配置
[system]
    #启动地址
    address="127.0.0.1:95"
    #权限配置路径
    rbac_path="./config/rbac.conf"
    #是否开启跨域
    cors=true
    #是否开发调试模式
    debug=true
#权限配置文件目录
[casbin]
    path="rbac.conf"

#接口请求日志
[log]
    #是否开启日志
    close=false
    #文件最长保存时间(小时)
    maximum=168
    #分割时间(小时)
    split=24

#主库设置
[database]
    connection="mysql"
    host="47.103.147.249"
    port="3306"
    database="ekgo"
    username="root"
    password="pi3.1415926"
    config="charset=utf8mb4&parseTime=True&loc=Local"
    log=true
#阿里云配置
[oss]
    key_id=""
    key_secret=""
    endpoint=""
    bucket=""

#Redis配置
[redis]
    address="localhost:6379"
    password=""
    db=0
#邮箱警报发送
[emaill]
    switch=true
    to=['56494565@qq.com']
    from= '56494565@qq.com'
    host= 'smtp.qq.com:25'
    secret= 'fdtshicbbvybbiic'
#Json web token
[jwt]
    private_key=''
    public_key=''